# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              DS4MP
description:        Intro. course in data science for public policy and management students

# Site subpath, e.g. /blog
baseurl:            "/ddmp-uw-class-spring-2019"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://ds4ps.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Data-Driven Management & Policy      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Jesse Lecy
    github:     lecy   # Github username for avatar


github_info:
    username:          ds4ps # Github location of the course
    branch:            master
    website-repo:      ddmp-uw-class-spring-2019
    course-repo:       Data-Science-Class

index:
    title: Data-Driven Management and Policy
    image: imac.svg
    subtitle: The course will cover ways that data can be used to improve performance in public organizations, as well as tools and techniques for collecting, analyzing, and displaying data.  Thus, an emphasis will both be placed on the substantive idea behind using data for performance management as well as programming.  The class will be taught in R software and will introduce students to its language, structure, and capabilities for data analysis.   Through  R,  students  will  become  comfortable  inputting,  manipulating,  and  visualizing  data  through  the  software.  In addition to the technical skills gained, students will be introduced to how data can drive performance management through a self-directed project and understand the potential and possible abuses of data to drive public organizations.  As part of the class, students will collect their own data, use that data in  an  individual  experiment  to  test  performance,  and  display  the  outcome  using  a  ’dashboard’ in R.
    


header:
- title: Syllabus
  url: /
  
- title: Course Schedule
  url: schedule/

- title: Textbook
  url: https://ds4ps.github.io/Data-Science-Class/TEXTBOOK/docs/index.html 

# - title: Datasets
#  url: datasets/

- title: Resources
  url: resources/

- title: Get Help
  url: discussions/


footer:
- title: Home
  url: /

- title: Datasets
  url: /datasets/

- title: Textbook
  url:  https://bookdown.org/yihui/bookdown-demo/

- title: Course Schedule
  url: /schedule/







# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jesse:
        name:       Jesse Lecy
        github:     lecy    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/asupublicservice
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/asupublicservice/
    linkedin:       https://www.linkedin.com/school/asupublicservice/
    pinterest:
    twitter:        https://twitter.com/asupublicsvc
    vimeo:          
    youtube:        https://www.youtube.com/user/coppvideos

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://www.youtube.com/watch?v=WUAcN9UCnbU">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   UA-123960540-1

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true



course_url: "https://ds4ps.github.io/Data-Science-Class/"

